# Generated by Django 5.0.6 on 2024-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_object',
            field=models.ManyToManyField(to='store.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_object',
            field=models.ManyToManyField(to='store.tag'),
        ),
    ]
