# Generated by Django 5.0.6 on 2024-06-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitems',
            name='basket_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='store.basket'),
        ),
    ]
