# Generated by Django 5.0.6 on 2024-06-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_basketitems_basket_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
